# Pandas

Pandas is a Python library.

Pandas is used to analyze data.

# What is Pandas

Pandas is a Python library used for working with data sets.

It has functions for analyzing, cleaning, exploring, and manipulating data.

The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.

# Why Use Pandas?

Pandas allows us to analyze big data and make conclusions based on statistical theories.

Pandas can clean messy data sets, and make them readable and relevant.

Relevant data is very important in data science.

# What Can Pandas Do?

Pandas gives you answers about the data. Like:

Is there a correlation between two or more columns?
What is average value?
Max value?
Min value?
Pandas are also able to delete rows that are not relevant, or contains wrong values, like empty or NULL values. This is called cleaning the data.

# Where is the Pandas Codebase?

The source code for Pandas is located at this github repository https://github.com/pandas-dev/pandas

In [1]:
import pandas as pd
import numpy as np

In [2]:
dict1 = {
    "name":['harry', 'rohan', 'skillf', 'shubh'],
    "marks":[92, 34, 24, 17],
    "city":['rampur', 'kolkata', 'bareilly', 'antarctica']
}

In [3]:
df = pd.DataFrame(dict1)

In [4]:
df

     name  marks        city
0   harry     92      rampur
1   rohan     34     kolkata
2  skillf     24    bareilly
3   shubh     17  antarctica

In [5]:
df.to_csv('friends.csv')

In [6]:
df.to_csv('friends_index_false.csv_',index=False)   # If False do not print fields for index names. Use index_label=False for easier importing in R.

# Head()

 The head() function in pandas displays the top rows of a DataFrame,

In [7]:
df.head(2)    #starting two show karta hai

    name  marks     city
0  harry     92   rampur
1  rohan     34  kolkata

# Tail()

 tail() function shows the bottom rows.

In [8]:
df.tail(2)  #last ka two show krta hai

     name  marks        city
2  skillf     24    bareilly
3   shubh     17  antarctica

# describe() Method

Definition and Usage
The describe() method returns description of the data in the DataFrame.

If the DataFrame contains numerical data, the description contains these information for each column:

count - The number of not-empty values.
mean - The average (mean) value.
std - The standard deviation.
min - the minimum value.
25% - The 25% percentile*.
50% - The 50% percentile*.
75% - The 75% percentile*.
max - the maximum value.

In [9]:
df.describe()

          marks
count   4.00000
mean   41.75000
std    34.21866
min    17.00000
25%    22.25000
50%    29.00000
75%    48.50000
max    92.00000

In [10]:
harry = pd.read_csv('Aman.csv')

In [11]:
harry

,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Train No,Speed,City
0,0,0,0,0,0,0,12314,50,kanpur
1,1,1,1,1,1,1,23424,123,kolkata
2,2,2,2,2,2,2,312242,67,meerut
3,3,3,3,3,3,3,123252,87,udisa

In [12]:
import pandas as pd
harry = pd.read_csv('Aman.csv')
print(harry)

   Unnamed: 0.5  Unnamed: 0.4  Unnamed: 0.3  Unnamed: 0.2  Unnamed: 0.1  \
0             0             0             0             0             0
1             1             1             1             1             1
2             2             2             2             2             2
3             3             3             3             3             3

   Unnamed: 0  Train No  Speed     City
0           0     12314     50   kanpur
1           1     23424    123  kolkata
2           2    312242     67   meerut
3           3    123252     87    udisa

In [13]:
harry['Speed']

0     50
1    123
2     67
3     87
Name: Speed, dtype: int64

In [14]:
harry['Speed'][0]

50

In [15]:
harry['Speed'][0] = 50

C:\Users\hp\AppData\Local\Temp\ipykernel_1888\805298609.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  harry['Speed'][0] = 50

In [16]:
harry

,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Train No,Speed,City
0,0,0,0,0,0,0,12314,50,kanpur
1,1,1,1,1,1,1,23424,123,kolkata
2,2,2,2,2,2,2,312242,67,meerut
3,3,3,3,3,3,3,123252,87,udisa

In [17]:
harry.to_csv('Aman.csv')

In [18]:
harry.index = ['first', 'second', 'third', 'fourth']

In [19]:
harry

,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Train No,Speed,City
first,0,0,0,0,0,0,12314,50,kanpur
second,1,1,1,1,1,1,23424,123,kolkata
third,2,2,2,2,2,2,312242,67,meerut
fourth,3,3,3,3,3,3,123252,87,udisa

# Series pandas

In [20]:
ser = pd.Series(np.random.rand(34))

In [21]:
ser

0     0.516338
1     0.603895
2     0.354802
3     0.290692
4     0.934855
5     0.951030
6     0.393053
7     0.759935
8     0.136903
9     0.312414
10    0.797214
11    0.048195
12    0.194995
13    0.635964
14    0.887454
15    0.760638
16    0.321689
17    0.846328
18    0.933972
19    0.624831
20    0.517244
21    0.672361
22    0.631267
23    0.581821
24    0.809475
25    0.165335
26    0.895968
27    0.950611
28    0.350146
29    0.377505
30    0.392608
31    0.805105
32    0.892506
33    0.663927
dtype: float64

In [22]:
type(ser)

pandas.core.series.Series

In [23]:
newdf = pd.DataFrame(np.random.rand(334,5), index=np.arange(334))   # np.arange function hota hai

In [24]:
newdf

            0         1         2         3         4
0    0.549007  0.065801  0.738237  0.212474  0.565647
1    0.409409  0.446972  0.021975  0.767540  0.762969
2    0.294539  0.828633  0.818971  0.679143  0.537662
3    0.523505  0.923607  0.561251  0.317839  0.683806
4    0.012582  0.021890  0.967910  0.607450  0.992860
..        ...       ...       ...       ...       ...
329  0.817108  0.457055  0.893436  0.079028  0.762803
330  0.625520  0.530572  0.132499  0.529086  0.688942
331  0.111310  0.696478  0.829859  0.495296  0.928678
332  0.386060  0.406395  0.654863  0.374641  0.472287
333  0.258559  0.306048  0.620448  0.264485  0.401248

[334 rows x 5 columns]

In [25]:
type(newdf)

pandas.core.frame.DataFrame

In [26]:
newdf.head()

          0         1         2         3         4
0  0.549007  0.065801  0.738237  0.212474  0.565647
1  0.409409  0.446972  0.021975  0.767540  0.762969
2  0.294539  0.828633  0.818971  0.679143  0.537662
3  0.523505  0.923607  0.561251  0.317839  0.683806
4  0.012582  0.021890  0.967910  0.607450  0.992860

In [27]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.489604    0.482439    0.508997    0.505856    0.512290
std      0.278787    0.293673    0.293103    0.280392    0.290690
min      0.001920    0.001745    0.003596    0.000045    0.002938
25%      0.264082    0.224167    0.268398    0.271439    0.251279
50%      0.483042    0.462832    0.520905    0.492499    0.538744
75%      0.720443    0.756471    0.762063    0.738299    0.739038
max      0.990457    0.998964    0.995937    0.998692    0.996720

In [28]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [29]:
newdf[0][0] = "Aman"

C:\Users\hp\AppData\Local\Temp\ipykernel_1888\706979197.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Aman' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0] = "Aman"

In [30]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [31]:
newdf.head()

          0         1         2         3         4
0      Aman  0.065801  0.738237  0.212474  0.565647
1  0.409409  0.446972  0.021975  0.767540  0.762969
2  0.294539  0.828633  0.818971  0.679143  0.537662
3  0.523505  0.923607  0.561251  0.317839  0.683806
4  0.012582  0.021890  0.967910  0.607450  0.992860

In [32]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int32', length=334)

In [33]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

Change Numpy Arrays karna chahta hu

In [34]:
newdf.to_numpy()

array([['Aman', 0.065801164066141, 0.7382373503520884,
        0.21247428004703062, 0.5656473904468039],
       [0.40940899951383825, 0.4469723731170544, 0.021974947187042404,
        0.7675400512798513, 0.7629692059248333],
       [0.29453902526808573, 0.8286332349943716, 0.8189714869931093,
        0.6791425734784098, 0.5376623008332018],
       ...,
       [0.11131023266150264, 0.6964776761450034, 0.8298593282314924,
        0.4952960546754569, 0.9286780047953013],
       [0.3860596302812177, 0.406394515714389, 0.6548633235963832,
        0.3746412034023249, 0.47228730607021474],
       [0.25855917222197045, 0.30604820368796604, 0.620447944038557,
        0.2644846797932696, 0.40124776811561247]], dtype=object)

change Aman to 0.3

In [35]:
newdf[0][0] = 0.3

In [36]:
newdf.head()

          0         1         2         3         4
0       0.3  0.065801  0.738237  0.212474  0.565647
1  0.409409  0.446972  0.021975  0.767540  0.762969
2  0.294539  0.828633  0.818971  0.679143  0.537662
3  0.523505  0.923607  0.561251  0.317839  0.683806
4  0.012582  0.021890  0.967910  0.607450  0.992860

# Transpose

In [37]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.3,0.409409,0.294539,0.523505,0.012582,0.545576,0.538547,0.273044,0.878818,0.418229,...,0.87857,0.599458,0.779451,0.050963,0.719815,0.817108,0.62552,0.11131,0.38606,0.258559
1,0.065801,0.446972,0.828633,0.923607,0.02189,0.998964,0.503048,0.263536,0.53436,0.253287,...,0.163193,0.866092,0.928396,0.146247,0.189258,0.457055,0.530572,0.696478,0.406395,0.306048
2,0.738237,0.021975,0.818971,0.561251,0.96791,0.891183,0.750303,0.753195,0.215124,0.12197,...,0.526963,0.041143,0.665505,0.962396,0.842346,0.893436,0.132499,0.829859,0.654863,0.620448
3,0.212474,0.76754,0.679143,0.317839,0.60745,0.306197,0.801441,0.717792,0.449343,0.718107,...,0.472143,0.553359,0.529202,0.53163,0.713767,0.079028,0.529086,0.495296,0.374641,0.264485
4,0.565647,0.762969,0.537662,0.683806,0.99286,0.281112,0.253126,0.241662,0.681407,0.530535,...,0.681223,0.071205,0.358429,0.243666,0.342596,0.762803,0.688942,0.928678,0.472287,0.401248

In [38]:
newdf.head()

          0         1         2         3         4
0       0.3  0.065801  0.738237  0.212474  0.565647
1  0.409409  0.446972  0.021975  0.767540  0.762969
2  0.294539  0.828633  0.818971  0.679143  0.537662
3  0.523505  0.923607  0.561251  0.317839  0.683806
4  0.012582  0.021890  0.967910  0.607450  0.992860

# Sort Opposite row

In [39]:
newdf.sort_index(axis=0, ascending=False)  # axis=0 rows hota hai

            0         1         2         3         4
333  0.258559  0.306048  0.620448  0.264485  0.401248
332   0.38606  0.406395  0.654863  0.374641  0.472287
331   0.11131  0.696478  0.829859  0.495296  0.928678
330   0.62552  0.530572  0.132499  0.529086  0.688942
329  0.817108  0.457055  0.893436  0.079028  0.762803
..        ...       ...       ...       ...       ...
4    0.012582  0.021890  0.967910  0.607450  0.992860
3    0.523505  0.923607  0.561251  0.317839  0.683806
2    0.294539  0.828633  0.818971  0.679143  0.537662
1    0.409409  0.446972  0.021975  0.767540  0.762969
0         0.3  0.065801  0.738237  0.212474  0.565647

[334 rows x 5 columns]

# Sort Opposite Columns

In [40]:
newdf.sort_index(axis=1, ascending=False)   # asis = 1 columns hoti hai

            4         3         2         1         0
0    0.565647  0.212474  0.738237  0.065801       0.3
1    0.762969  0.767540  0.021975  0.446972  0.409409
2    0.537662  0.679143  0.818971  0.828633  0.294539
3    0.683806  0.317839  0.561251  0.923607  0.523505
4    0.992860  0.607450  0.967910  0.021890  0.012582
..        ...       ...       ...       ...       ...
329  0.762803  0.079028  0.893436  0.457055  0.817108
330  0.688942  0.529086  0.132499  0.530572   0.62552
331  0.928678  0.495296  0.829859  0.696478   0.11131
332  0.472287  0.374641  0.654863  0.406395   0.38606
333  0.401248  0.264485  0.620448  0.306048  0.258559

[334 rows x 5 columns]

# Type

In [41]:
newdf[0]

0           0.3
1      0.409409
2      0.294539
3      0.523505
4      0.012582
         ...
329    0.817108
330     0.62552
331     0.11131
332     0.38606
333    0.258559
Name: 0, Length: 334, dtype: object

In [42]:
type(newdf[0])

pandas.core.series.Series

In [43]:
newdf.head()

          0         1         2         3         4
0       0.3  0.065801  0.738237  0.212474  0.565647
1  0.409409  0.446972  0.021975  0.767540  0.762969
2  0.294539  0.828633  0.818971  0.679143  0.537662
3  0.523505  0.923607  0.561251  0.317839  0.683806
4  0.012582  0.021890  0.967910  0.607450  0.992860

# .copy()

In Pandas, .copy() is a method that creates a copy of a DataFrame or a Series. This method returns a fully independent copy of DataFrame or a shallow copy (see Shallow vs. Deep Copy section).

Syntax
df_copy = df.copy()


The boolean parameter deep specifies whether .copy() should create a deep or a shallow copy. The default value is deep=True, which enforces a deep copy.

In [44]:
newdf2 = newdf.copy()

In [45]:
newdf2[0][0] = 97835

C:\Users\hp\AppData\Local\Temp\ipykernel_1888\3150214023.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf2[0][0] = 97835

In [46]:
newdf

            0         1         2         3         4
0         0.3  0.065801  0.738237  0.212474  0.565647
1    0.409409  0.446972  0.021975  0.767540  0.762969
2    0.294539  0.828633  0.818971  0.679143  0.537662
3    0.523505  0.923607  0.561251  0.317839  0.683806
4    0.012582  0.021890  0.967910  0.607450  0.992860
..        ...       ...       ...       ...       ...
329  0.817108  0.457055  0.893436  0.079028  0.762803
330   0.62552  0.530572  0.132499  0.529086  0.688942
331   0.11131  0.696478  0.829859  0.495296  0.928678
332   0.38606  0.406395  0.654863  0.374641  0.472287
333  0.258559  0.306048  0.620448  0.264485  0.401248

[334 rows x 5 columns]

#loc
Access a group of rows and columns by label(s) or a boolean array.

In [47]:
newdf.loc[0,0] = 654

In [48]:
newdf.head(2)

          0         1         2         3         4
0       654  0.065801  0.738237  0.212474  0.565647
1  0.409409  0.446972  0.021975  0.767540  0.762969

# Columns Change

In [49]:
newdf.columns = list("ABCDE")

In [50]:
newdf

            A         B         C         D         E
0         654  0.065801  0.738237  0.212474  0.565647
1    0.409409  0.446972  0.021975  0.767540  0.762969
2    0.294539  0.828633  0.818971  0.679143  0.537662
3    0.523505  0.923607  0.561251  0.317839  0.683806
4    0.012582  0.021890  0.967910  0.607450  0.992860
..        ...       ...       ...       ...       ...
329  0.817108  0.457055  0.893436  0.079028  0.762803
330   0.62552  0.530572  0.132499  0.529086  0.688942
331   0.11131  0.696478  0.829859  0.495296  0.928678
332   0.38606  0.406395  0.654863  0.374641  0.472287
333  0.258559  0.306048  0.620448  0.264485  0.401248

[334 rows x 5 columns]

In [51]:
newdf.columns = list("ABCDE")

In [52]:
newdf.head(2)

          A         B         C         D         E
0       654  0.065801  0.738237  0.212474  0.565647
1  0.409409  0.446972  0.021975  0.767540  0.762969

# loc[] method

Pandas DataFrame.loc attribute accesses a group of rows and columns by label(s) or a boolean array in the given

loc function se value chamge hota hai

In [53]:
newdf.loc[0,'A'] = 65445

In [54]:
newdf.head()

          A         B         C         D         E
0     65445  0.065801  0.738237  0.212474  0.565647
1  0.409409  0.446972  0.021975  0.767540  0.762969
2  0.294539  0.828633  0.818971  0.679143  0.537662
3  0.523505  0.923607  0.561251  0.317839  0.683806
4  0.012582  0.021890  0.967910  0.607450  0.992860

# columns find karne ke liye

In [55]:
newdf.loc[[1,2], ['C', 'D']]

          C         D
1  0.021975  0.767540
2  0.818971  0.679143

sare rows find kare ke liye

In [56]:
newdf.loc[:, ['C', 'D']]

            C         D
0    0.738237  0.212474
1    0.021975  0.767540
2    0.818971  0.679143
3    0.561251  0.317839
4    0.967910  0.607450
..        ...       ...
329  0.893436  0.079028
330  0.132499  0.529086
331  0.829859  0.495296
332  0.654863  0.374641
333  0.620448  0.264485

[334 rows x 2 columns]

sare columns find kare ke liye

In [57]:
newdf.loc[[1,2], :]

          A         B         C         D         E
1  0.409409  0.446972  0.021975  0.767540  0.762969
2  0.294539  0.828633  0.818971  0.679143  0.537662

In [58]:
newdf.loc[(newdf['A']<0.3)]

            A         B         C         D         E
2    0.294539  0.828633  0.818971  0.679143  0.537662
4    0.012582  0.021890  0.967910  0.607450  0.992860
7    0.273044  0.263536  0.753195  0.717792  0.241662
11   0.239347  0.885429  0.590597  0.840256  0.904368
15   0.241956  0.133186  0.387148  0.050398  0.541097
..        ...       ...       ...       ...       ...
317  0.278918  0.850610  0.608493  0.062588  0.688495
323   0.02654  0.747554  0.545523  0.966774  0.082791
327  0.050963  0.146247  0.962396  0.531630  0.243666
331   0.11131  0.696478  0.829859  0.495296  0.928678
333  0.258559  0.306048  0.620448  0.264485  0.401248

[105 rows x 5 columns]

In [59]:
newdf.head(2)

          A         B         C         D         E
0     65445  0.065801  0.738237  0.212474  0.565647
1  0.409409  0.446972  0.021975  0.767540  0.762969

# iloc dataframe

# Syntax


dataframe.iloc[row, column]

Return the the value of the second [1] row of the first [0] column:

In [60]:
newdf.iloc[1,0]

0.40940899951383825

In [61]:
newdf.iloc[[0,5], [1,2]]

          B         C
0  0.065801  0.738237
5  0.998964  0.891183

In [62]:
newdf.head(3)

          A         B         C         D         E
0     65445  0.065801  0.738237  0.212474  0.565647
1  0.409409  0.446972  0.021975  0.767540  0.762969
2  0.294539  0.828633  0.818971  0.679143  0.537662

# pandas.DataFrame.drop

the drop() method removes the specified column.

In [63]:
newdf.drop([0])

            A         B         C         D         E
1    0.409409  0.446972  0.021975  0.767540  0.762969
2    0.294539  0.828633  0.818971  0.679143  0.537662
3    0.523505  0.923607  0.561251  0.317839  0.683806
4    0.012582  0.021890  0.967910  0.607450  0.992860
5    0.545576  0.998964  0.891183  0.306197  0.281112
..        ...       ...       ...       ...       ...
329  0.817108  0.457055  0.893436  0.079028  0.762803
330   0.62552  0.530572  0.132499  0.529086  0.688942
331   0.11131  0.696478  0.829859  0.495296  0.928678
332   0.38606  0.406395  0.654863  0.374641  0.472287
333  0.258559  0.306048  0.620448  0.264485  0.401248

[333 rows x 5 columns]

the drop() method removes the specified rows.

In [64]:
newdf.drop(['A'], axis=1)

            B         C         D         E
0    0.065801  0.738237  0.212474  0.565647
1    0.446972  0.021975  0.767540  0.762969
2    0.828633  0.818971  0.679143  0.537662
3    0.923607  0.561251  0.317839  0.683806
4    0.021890  0.967910  0.607450  0.992860
..        ...       ...       ...       ...
329  0.457055  0.893436  0.079028  0.762803
330  0.530572  0.132499  0.529086  0.688942
331  0.696478  0.829859  0.495296  0.928678
332  0.406395  0.654863  0.374641  0.472287
333  0.306048  0.620448  0.264485  0.401248

[334 rows x 4 columns]

In [65]:
newdf.drop(['A', 'C'], axis=1)

            B         D         E
0    0.065801  0.212474  0.565647
1    0.446972  0.767540  0.762969
2    0.828633  0.679143  0.537662
3    0.923607  0.317839  0.683806
4    0.021890  0.607450  0.992860
..        ...       ...       ...
329  0.457055  0.079028  0.762803
330  0.530572  0.529086  0.688942
331  0.696478  0.495296  0.928678
332  0.406395  0.374641  0.472287
333  0.306048  0.264485  0.401248

[334 rows x 3 columns]

In [66]:
newdf.drop(['A', 'D'], axis=1, inplace=True)

In [67]:
newdf

            B         C         E
0    0.065801  0.738237  0.565647
1    0.446972  0.021975  0.762969
2    0.828633  0.818971  0.537662
3    0.923607  0.561251  0.683806
4    0.021890  0.967910  0.992860
..        ...       ...       ...
329  0.457055  0.893436  0.762803
330  0.530572  0.132499  0.688942
331  0.696478  0.829859  0.928678
332  0.406395  0.654863  0.472287
333  0.306048  0.620448  0.401248

[334 rows x 3 columns]

In [68]:
newdf.drop([1, 5], axis=0, inplace=True)

In [69]:
newdf

            B         C         E
0    0.065801  0.738237  0.565647
2    0.828633  0.818971  0.537662
3    0.923607  0.561251  0.683806
4    0.021890  0.967910  0.992860
6    0.503048  0.750303  0.253126
..        ...       ...       ...
329  0.457055  0.893436  0.762803
330  0.530572  0.132499  0.688942
331  0.696478  0.829859  0.928678
332  0.406395  0.654863  0.472287
333  0.306048  0.620448  0.401248

[332 rows x 3 columns]

In [70]:
newdf.head(3)

          B         C         E
0  0.065801  0.738237  0.565647
2  0.828633  0.818971  0.537662
3  0.923607  0.561251  0.683806

#  reset_index() Method

The reset_index() method allows you reset the index back to the default 0, 1, 2 etc indexes.

By default this method will keep the "old" idexes in a column named "index", to avoid this, use the drop parameter.

In [71]:
newdf.reset_index(drop=True, inplace=True)

In [72]:
newdf.head(3)

          B         C         E
0  0.065801  0.738237  0.565647
1  0.828633  0.818971  0.537662
2  0.923607  0.561251  0.683806

# isnull() Method

The isnull() method returns a DataFrame object where all the values are replaced with a Boolean value True for NULL values, and otherwise False.

In [73]:
newdf['B'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
327    False
328    False
329    False
330    False
331    False
Name: B, Length: 332, dtype: bool

B me NONE lana hai

In [74]:
newdf.loc[:, ['B']] = None

In [75]:
newdf

        B         C         E
0    None  0.738237  0.565647
1    None  0.818971  0.537662
2    None  0.561251  0.683806
3    None  0.967910  0.992860
4    None  0.750303  0.253126
..    ...       ...       ...
327  None  0.893436  0.762803
328  None  0.132499  0.688942
329  None  0.829859  0.928678
330  None  0.654863  0.472287
331  None  0.620448  0.401248

[332 rows x 3 columns]

In [76]:
newdf

        B         C         E
0    None  0.738237  0.565647
1    None  0.818971  0.537662
2    None  0.561251  0.683806
3    None  0.967910  0.992860
4    None  0.750303  0.253126
..    ...       ...       ...
327  None  0.893436  0.762803
328  None  0.132499  0.688942
329  None  0.829859  0.928678
330  None  0.654863  0.472287
331  None  0.620448  0.401248

[332 rows x 3 columns]

In [77]:
newdf.loc[:, ['B']] = 34

In [78]:
newdf

      B         C         E
0    34  0.738237  0.565647
1    34  0.818971  0.537662
2    34  0.561251  0.683806
3    34  0.967910  0.992860
4    34  0.750303  0.253126
..   ..       ...       ...
327  34  0.893436  0.762803
328  34  0.132499  0.688942
329  34  0.829859  0.928678
330  34  0.654863  0.472287
331  34  0.620448  0.401248

[332 rows x 3 columns]

In [79]:
newdf.head()

    B         C         E
0  34  0.738237  0.565647
1  34  0.818971  0.537662
2  34  0.561251  0.683806
3  34  0.967910  0.992860
4  34  0.750303  0.253126

In [80]:
df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwomen'],
                   "toy": [np.nan, 'Batmobile', 'Bullwhip'],
                   "born": [pd.NaT, pd.Timestamp("1940-04-25"),
                            pd.NaT]})

In [81]:
df.head()

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwomen   Bullwhip        NaT

In [82]:
df.dropna()

     name        toy       born
1  Batman  Batmobile 1940-04-25

In [83]:
df.dropna(how='all')

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwomen   Bullwhip        NaT

In [84]:
df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwomen'],
                   "toy": [np.nan, np.nan, np.nan],
                   "born": [pd.NaT, pd.Timestamp("1940-04-25"),
                            pd.NaT]})

In [85]:
df.head()

       name  toy       born
0    Alfred  NaN        NaT
1    Batman  NaN 1940-04-25
2  Catwomen  NaN        NaT

In [86]:
df.dropna(how='all', axis=1)

       name       born
0    Alfred        NaT
1    Batman 1940-04-25
2  Catwomen        NaT

In [87]:
df.drop_duplicates(subset=['name'])

       name  toy       born
0    Alfred  NaN        NaT
1    Batman  NaN 1940-04-25
2  Catwomen  NaN        NaT

# drop_duplicates

Return Series with duplicate values removed.
Parameters:
keep{‘first’, ‘last’, False}, default ‘first’
Method to handle dropping duplicates:

‘first’ : Drop duplicates except for the first occurrence.

‘last’ : Drop duplicates except for the last occurrence.

False : Drop all duplicates.

In [88]:
s = pd.Series(['llama', 'cow', 'llama', 'beetle', 'llama', 'hippo'],
              name='animal')

In [90]:
s.drop_duplicates()

0     llama
1       cow
3    beetle
5     hippo
Name: animal, dtype: object

‘last’ : Drop duplicates except for the last occurrence.

In [91]:
s.drop_duplicates(keep='last')

1       cow
3    beetle
4     llama
5     hippo
Name: animal, dtype: object

False : Drop all duplicates.

In [92]:
s.drop_duplicates(keep=False)

1       cow
3    beetle
5     hippo
Name: animal, dtype: object

In [93]:
df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwomen'],
                   "toy": [np.nan, np.nan, np.nan],
                   "born": [pd.NaT, pd.Timestamp("1940-04-25"),
                            pd.NaT]})

In [95]:
df.head()

       name  toy       born
0    Alfred  NaN        NaT
1    Batman  NaN 1940-04-25
2  Catwomen  NaN        NaT

In [94]:
df.shape

(3, 3)

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   toy     0 non-null      float64
 2   born    1 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 204.0+ bytes

# notnull()

In [97]:
df.notnull()

   name    toy   born
0  True  False  False
1  True  False   True
2  True  False  False

# isnull()

In [98]:
df.isnull()

    name   toy   born
0  False  True   True
1  False  True  False
2  False  True   True